### 1) Give an example of a list and write a python program to swap the first and last element of the list.

### 2) Give an example of two negative numbers and write a python code to find the maximum and minimum of these two numbers.

### 5) Write a python program to merge two dictionaries.

In [2]:
Car_Brand = ['Toyota', 'Mazda', 'Land Rovers', 'Mercedez Benz', 'Honda', 'Lexus']

In [3]:
Car_Brand

['Toyota', 'Mazda', 'Land Rovers', 'Mercedez Benz', 'Honda', 'Lexus']

In [4]:
def swaplist(Car_Brand):
    first = Car_Brand.pop(0)
    last = Car_Brand.pop(-1)
    
    Car_Brand.insert(0, last)
    Car_Brand.append(first)
    
    return Car_Brand

newCar_Brand = ['Toyota', 'Mazda', 'Land Rovers', 'Mercedez Benz', 'Honda', 'Lexus']

In [5]:
swaplist(newCar_Brand)

['Lexus', 'Mazda', 'Land Rovers', 'Mercedez Benz', 'Honda', 'Toyota']

SOLUTION TO QUESTION NUMBER 2

In [13]:
def maximum(a, b):
    if a >= b:
        return a
    else:
        return b

a = -25
b = -13

print(maximum(a,b))

-13


In [14]:
def minimum (a,b):
    if a<=b:
        return a
    else:
        return b
    a = -25
    b = -13
    
print(minimum(a,b))    

-25


In [15]:
a = -25
b = -13
maximum = max(a,b)
print (maximum)

-13


In [16]:
a = -25
b = -13
minimum = min(a,b)
print (minimum)

-25


# SOLUTION TO QUESTION NUMBER 5

In [17]:
Car_brands = ['Toyota','Nissan','Mercedes-Benz','Lexus','RangeRover','Honda']

Car_Models = ['Camry','Primera','E350','Rx350','Velar','Accord']

In [18]:
Car_brands + Car_Models

['Toyota',
 'Nissan',
 'Mercedes-Benz',
 'Lexus',
 'RangeRover',
 'Honda',
 'Camry',
 'Primera',
 'E350',
 'Rx350',
 'Velar',
 'Accord']

# PART 2

### 1) Write a pandas program to insert a new column in existing dataframe. Sample python dictionary data and list labels:
exam_data = {'name':['Anastasia, 'Dima','Katherne','James','Emily','Micheal','Matthew','Laura','Kevin','Jones'], 'score': [12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19], 'attempts':[1,3,2,3,2,3,1,1,2,1], 'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']}
Labels = ['a','b','c','d','e','f','g','h','i','j']
                     
### 2) Write a pandas program to iterate over rows in a data frame. Sample python dictionary data and list labels: 
exam_data = [{'name': 'Anastasia','score': 12.5}, {'name': 'Dima','score':9}, {'name': 'Katherine','score':16.5}]
                     
### 3) Write a pandas program to get list from dataframe column headers. Sample python dictionary data and list labels:
exam_data = {'name':['Anastasia, 'Dima','Katherne','James','Emily','Micheal','Matthew','Laura','Kevin','Jones'], 'score': [12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19], 'attempts':[1,3,2,3,2,3,1,1,2,1], 'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']}
Labels = ['a','b','c','d','e','f','g','h','i','j']

### SOLUTION TO QUESTION NUMBER 1

In [19]:
import pandas as pd
import numpy as np

In [20]:
exam_data = {'name':['Anastasia', 'Dima','Katherne','James','Emily','Micheal','Matthew','Laura','Kevin','Jones'], 'score': [12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19], 'attempts':[1,3,2,3,2,3,1,1,2,1], 'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']}
Labels = ['a','b','c','d','e','f','g','h','i','j']
df = pd.DataFrame(exam_data, index = Labels)
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c   Katherne   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Micheal   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jones   19.0         1     yes

In [21]:
df['class year'] = 10

In [22]:
df

name  score  attempts qualify  class year
a  Anastasia   12.5         1     yes          10
b       Dima    9.0         3      no          10
c   Katherne   16.5         2     yes          10
d      James    NaN         3      no          10
e      Emily    9.0         2      no          10
f    Micheal   20.0         3     yes          10
g    Matthew   14.5         1     yes          10
h      Laura    NaN         1      no          10
i      Kevin    8.0         2      no          10
j      Jones   19.0         1     yes          10

In [23]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
class_year = np.arange(0,10)

In [25]:
len(class_year)

10

In [26]:
class_year = df['class year']

In [27]:
np.random.randint(1,7, size=10)

array([3, 6, 1, 1, 6, 1, 2, 4, 4, 1])

In [28]:
len(np.random.randint(1,7, size=10))

10

In [29]:
int_class_year = np.random.randint(1,7, size=10)

In [30]:
int_class_year

array([2, 4, 5, 1, 3, 3, 4, 1, 6, 6])

In [31]:
df['class year'] = int_class_year

In [32]:
df

name  score  attempts qualify  class year
a  Anastasia   12.5         1     yes           2
b       Dima    9.0         3      no           4
c   Katherne   16.5         2     yes           5
d      James    NaN         3      no           1
e      Emily    9.0         2      no           3
f    Micheal   20.0         3     yes           3
g    Matthew   14.5         1     yes           4
h      Laura    NaN         1      no           1
i      Kevin    8.0         2      no           6
j      Jones   19.0         1     yes           6

### SOLUTION TO QUESTION NUMBER 2

In [33]:
exam_data = {'name':['Anastasia', 'Dima','Katherne'],'score': [12.5,9,16.5],'attempts':[1,3,2], 'qualify':['yes','no','yes']}
Labels = ['a','b','c']
df = pd.DataFrame(exam_data, index = Labels)
df                     

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c   Katherne   16.5         2     yes

In [34]:
df[['name', 'score']]

name  score
a  Anastasia   12.5
b       Dima    9.0
c   Katherne   16.5

In [35]:
df[['attempts', 'qualify']]

attempts qualify
a         1     yes
b         3      no
c         2     yes

### SOLUTION TO QUESTION NUMBER 3

In [37]:
import pandas as pd
import numpy as np

In [38]:
exam_data = {'name':['Anastasia', 'Dima','Katherne','James','Emily','Micheal','Matthew','Laura','Kevin','Jones'], 'score': [12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19], 'attempts':[1,3,2,3,2,3,1,1,2,1], 'qualify':['yes','no','yes','no','no','yes','yes','no','no','yes']}
Labels = ['a','b','c','d','e','f','g','h','i','j']
df = pd.DataFrame(exam_data, index = Labels)
df

name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c   Katherne   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Micheal   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jones   19.0         1     yes

In [39]:
df.columns

Index(['name', 'score', 'attempts', 'qualify'], dtype='object')